# Generated by Django 4.1.3 on 2022-11-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_name_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iou',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_user', to='apis.user'),
        ),
        migrations.AlterField(
            model_name='iou',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenders_user', to='apis.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
